include:
  - project: 'flomation/infrastructure/ci-templates'
    ref: main
    file: '.gitlab-ci-templates.yml'

stages:
  - prepare
  - test
  - build
  - rpm-publish
  - deb-publish
  - publish
  - docker-prepare
  - docker
  - Development
  - Production

variables:
  VERSION: 1.0.${CI_PIPELINE_IID}
  NAME: runner
  AWS_ACCESS_KEY_ID: ${GITLAB_AWS_USER_KEY}
  AWS_SECRET_ACCESS_KEY: ${GITLAB_AWS_USER_SECRET}
  AWS_DEFAULT_REGION: eu-west-2
  DEPLOY_BUCKET: ${AWS_DEPLOYMENT_BUCKET}
  HARBOR_IMAGE_PATH: ${HARBOR_REGISTRY}/${HARBOR_PROJECT}/${IMAGE_NAME}
  CI_TEMPLATES_PROJECT: flomation/infrastructure/ci-templates

inject-metadata:
  extends: .inject-metadata-template

lint:
  stage: prepare
  script:
    - make lint

compile:
  stage: build
  script:
    - make build
  artifacts:
    paths:
      - ./build.zip
      - ./dist/flomation*
    expire_in: 1 hour
  cache:
    policy: push
    paths:
      - ./build.zip

build-rpm-8:
  extends: .build-rpm-template
  image: rockylinux/rockylinux:8
  variables:
    EL_VERSION: "8"
    CI_TEMPLATES_REF: "main"
    APPLICATION_BINARY: "${PACKAGE_NAME}-amd64-linux*"
    ARCH: x86_64
  needs:
    - inject-metadata
    - compile
  artifacts:
    paths:
      - ${PACKAGE_NAME}-*el8.*.rpm
    expire_in: 30 days

build-rpm-9:
  extends: .build-rpm-template
  image: rockylinux/rockylinux:9
  variables:
    EL_VERSION: "9"
    CI_TEMPLATES_REF: "main"
    APPLICATION_BINARY: "${PACKAGE_NAME}-amd64-linux*"
    ARCH: x86_64
  needs:
    - inject-metadata
    - compile
  artifacts:
    paths:
      - ${PACKAGE_NAME}-*el9.*.rpm
    expire_in: 30 days

build-rpm-8-arm64:
  extends: .build-rpm-template
  image: rockylinux/rockylinux:8
  variables:
    EL_VERSION: "8"
    CI_TEMPLATES_REF: "main"
    APPLICATION_BINARY: "${PACKAGE_NAME}-arm64-linux*"
    ARCH: aarch64
  needs:
    - inject-metadata
    - compile
  artifacts:
    paths:
      - ${PACKAGE_NAME}-*el8.*.rpm
    expire_in: 30 days

build-rpm-9-arm64:
  extends: .build-rpm-template
  image: rockylinux/rockylinux:9
  variables:
    EL_VERSION: "9"
    CI_TEMPLATES_REF: "main"
    APPLICATION_BINARY: "${PACKAGE_NAME}-arm64-linux*"
    ARCH: aarch64
  needs:
    - inject-metadata
    - compile
  artifacts:
    paths:
      - ${PACKAGE_NAME}-*el9.*.rpm
    expire_in: 30 days

build-deb:
  extends: .build-deb-template
  variables:
    CI_TEMPLATES_REF: "main"
    APPLICATION_BINARY: "${PACKAGE_NAME}-amd64-linux*"
    ARCH: amd64
  needs:
    - inject-metadata
    - compile
  artifacts:
    paths:
      - ${PACKAGE_NAME}_*.deb
    expire_in: 30 days

build-deb-arm64:
  extends: .build-deb-template
  variables:
    CI_TEMPLATES_REF: "main"
    APPLICATION_BINARY: "${PACKAGE_NAME}-arm64-linux*"
    ARCH: arm64
  needs:
    - inject-metadata
    - compile
  artifacts:
    paths:
      - ${PACKAGE_NAME}_*.deb
    expire_in: 30 days

build-msi:
  extends: .build-msi-template
  variables:
    CI_TEMPLATES_REF: "main"
    APPLICATION_BINARY: "${PACKAGE_NAME}-amd64-windows*"
    ARCH: x64
  needs:
    - inject-metadata
    - compile
  artifacts:
    paths:
      - ${PACKAGE_NAME}-*.msi
    expire_in: 30 days

publish:
  stage: publish
  only:
    - main
  script:
    - aws s3 cp build.zip s3://${DEPLOY_BUCKET}/${NAME}/${CI_PIPELINE_IID}.zip
    - aws s3 cp build.zip s3://${DEPLOY_BUCKET}/${NAME}/latest.zip
  cache:
    policy: pull
    paths:
      - ./build.zip

publish-msi:
  extends: .publish-msi-template
  needs:
    - inject-metadata
    - build-msi

publish-rpm-8:
  extends: .publish-rpm-template
  variables:
    RPM_FILE_PATTERN: "${PACKAGE_NAME}-*el8.x86_64.rpm"
    EL_VERSION: "8"
    CI_TEMPLATES_REF: "main"
    ARCH: x86_64
    S3_ACCESS_KEY_PARAM: ${S3_ACCESS_KEY_PARAM_DEV}
    S3_SECRET_KEY_PARAM: ${S3_SECRET_KEY_PARAM_DEV}
  needs:
    - inject-metadata
    - build-rpm-8

publish-rpm-9:
  extends: .publish-rpm-template
  variables:
    RPM_FILE_PATTERN: "${PACKAGE_NAME}-*el9.x86_64.rpm"
    EL_VERSION: "9"
    CI_TEMPLATES_REF: "main"
    ARCH: x86_64
    S3_ACCESS_KEY_PARAM: ${S3_ACCESS_KEY_PARAM_DEV}
    S3_SECRET_KEY_PARAM: ${S3_SECRET_KEY_PARAM_DEV}
  needs:
    - inject-metadata
    - build-rpm-9

publish-rpm-8-arm64:
  extends: .publish-rpm-template
  variables:
    RPM_FILE_PATTERN: "${PACKAGE_NAME}-*el8.aarch64.rpm"
    EL_VERSION: "8"
    CI_TEMPLATES_REF: "main"
    ARCH: aarch64
    S3_ACCESS_KEY_PARAM: ${S3_ACCESS_KEY_PARAM_DEV}
    S3_SECRET_KEY_PARAM: ${S3_SECRET_KEY_PARAM_DEV}
  needs:
    - inject-metadata
    - build-rpm-8-arm64

publish-rpm-9-arm64:
  extends: .publish-rpm-template
  variables:
    RPM_FILE_PATTERN: "${PACKAGE_NAME}-*el9.aarch64.rpm"
    EL_VERSION: "9"
    CI_TEMPLATES_REF: "main"
    ARCH: aarch64
    S3_ACCESS_KEY_PARAM: ${S3_ACCESS_KEY_PARAM_DEV}
    S3_SECRET_KEY_PARAM: ${S3_SECRET_KEY_PARAM_DEV}
  needs:
    - inject-metadata
    - build-rpm-9-arm64

publish-deb:
  extends: .publish-deb-template
  variables:
    DEB_FILE_PATTERN: "${PACKAGE_NAME}_*_amd64.deb"
    CI_TEMPLATES_REF: "main"
    ARCH: amd64
    S3_ACCESS_KEY_PARAM: ${S3_ACCESS_KEY_PARAM_DEV}
    S3_SECRET_KEY_PARAM: ${S3_SECRET_KEY_PARAM_DEV}
  needs:
    - inject-metadata
    - build-deb

publish-deb-arm64:
  extends: .publish-deb-template
  variables:
    DEB_FILE_PATTERN: "${PACKAGE_NAME}_*_arm64.deb"
    CI_TEMPLATES_REF: "main"
    ARCH: arm64
    S3_ACCESS_KEY_PARAM: ${S3_ACCESS_KEY_PARAM_DEV}
    S3_SECRET_KEY_PARAM: ${S3_SECRET_KEY_PARAM_DEV}
  needs:
    - inject-metadata
    - build-deb-arm64

Deploy to DEV:
  stage: Development
  variables:
    ENVIRONMENT: dev
  only:
    - main
  script:
    - aws s3 cp s3://${DEPLOY_BUCKET}/deploy-application-aws.sh .
    - chmod +x deploy-application-aws.sh
    - ENVIRONMENT=${ENVIRONMENT} APPLICATION=${NAME} ./deploy-application-aws.sh

Deploy to Live:
  stage: Production
  when: manual
  variables:
    ENVIRONMENT: live
  only:
    - main
  script:
    - aws s3 cp s3://${DEPLOY_BUCKET}/deploy-application-aws.sh .
    - chmod +x deploy-application-aws.sh
    - ENVIRONMENT=${ENVIRONMENT} APPLICATION=${NAME} ./deploy-application-aws.sh

docker-prepare:
  stage: docker-prepare
  image: amazon/aws-cli:latest
  before_script:
    - yum install -y unzip
  script:
    - echo "Downloading and extracting runner and executor binaries from S3..."
    - aws s3 cp s3://${DEPLOY_BUCKET}/executor/latest.zip ./executor.zip
    - mkdir -p ./dist/
    - echo "Extracting executor binary..."
    - unzip -j executor.zip '*amd64-linux*' -d ./
    - mv *amd64-linux* ./dist/
    - echo "Binaries extracted:"
    - ls -lh ./dist/
    - rm -f latest.zip executor.zip
  needs:
    - inject-metadata
    - compile
  artifacts:
    paths:
      - ./dist/*flomation*amd64-linux*
    expire_in: 1 hour

build-docker-harbor:
  extends: .build-docker-dhi-harbor-buildx-template
  variables:
    BINARY_FILE_PATTERN: "dist/flomation-*-amd64-linux-*"
  needs:
    - inject-metadata
    - docker-prepare


build-docker:
  extends: .build-docker-dhi-buildx-template
  only:
    - main
  variables:
    BINARY_FILE_PATTERN: "dist/flomation-*-amd64-linux-*"
  needs:
    - inject-metadata
    - docker-prepare